DEMO_PRODUCT_TREE = {
    "name": "Checkout resilience",
    "tagline": "One checkout operation creates at most one customer charge.",
    "summary": {
        "coverage": 72,
        "drift": 14,
        "decisions": 1,
        "commits": 5,
    },
    "nodes": [
        {
            "id": "product",
            "parent": None,
            "kind": "product intent",
            "title": "Reliable checkout across payment retries",
            "summary": (
                "Recover from provider timeouts without duplicate charges, broken market "
                "contracts, or unsafe rollout. Refund policy remains unchanged."
            ),
            "owner": "Maya · Product",
            "state": "approved",
            "alignment": 100,
            "jira": "PAY-240",
            "original": "One checkout operation creates at most one charge.",
            "current": "Approved product brief · revision 3",
            "evidence": "Product outcome, four acceptance criteria, one explicit non-goal.",
            "action": "Product owner owns changes to business boundary.",
        },
        {
            "id": "epic-reconcile",
            "parent": "product",
            "kind": "epic",
            "title": "Payment reconciliation",
            "summary": "Reconcile pending payments inside five-minute settlement window.",
            "owner": "Arun · Tech lead",
            "state": "in progress",
            "alignment": 84,
            "jira": "PAY-241",
            "original": "Retry transient provider timeouts safely.",
            "current": "Two implementations reviewed; safe candidate ready.",
            "evidence": "Async safety, idempotency, and failure-path gates.",
            "action": "Merge safe candidate after reviewer approval.",
        },
        {
            "id": "task-retry",
            "parent": "epic-reconcile",
            "kind": "task",
            "title": "Build async retry worker",
            "summary": "Retry timeouts without blocking workers or duplicating provider effects.",
            "owner": "Nila · Developer",
            "state": "validated",
            "alignment": 100,
            "jira": "PAY-242",
            "original": "Three retries; stable operation ID; bounded concurrency.",
            "current": "Safe implementation proves one provider side effect.",
            "evidence": "Concurrency and timeout-after-success tests pass.",
            "action": "Ready for technical review.",
        },
        {
            "id": "commit-safe",
            "parent": "task-retry",
            "kind": "commit",
            "title": "Safe reconciliation candidate",
            "summary": "Async client plus idempotency key and adversarial timeout coverage.",
            "owner": "Nila · Developer",
            "state": "pass",
            "alignment": 100,
            "jira": "PAY-242",
            "commit": "2b7d867",
            "git_url": "https://github.com/JadeBear-09/codetrust-agent/pull/3",
            "original": "Never reconcile one payment more than once.",
            "current": "One operation ID produces one provider side effect.",
            "evidence": "CodeTrust PASS · risk 0/100 on PR #3.",
            "action": "Reviewer checks implementation quality; product intent remains satisfied.",
        },
        {
            "id": "commit-risky",
            "parent": "task-retry",
            "kind": "commit",
            "title": "First reconciliation candidate",
            "summary": "Plausible implementation failed idempotency, async, contract, and rollback gates.",
            "owner": "Nila · Developer",
            "state": "superseded",
            "alignment": 42,
            "jira": "PAY-242",
            "commit": "afbee71",
            "git_url": "https://github.com/JadeBear-09/codetrust-agent/pull/2",
            "original": "Safe retries with compatibility and rollback.",
            "current": "Happy path worked; four business-critical guarantees lacked proof.",
            "evidence": "CodeTrust BLOCK on PR #2; safe replacement exists.",
            "action": "Keep as trace showing why implementation changed.",
        },
        {
            "id": "epic-contract",
            "parent": "product",
            "kind": "epic",
            "title": "Compatibility and rollback",
            "summary": "Protect market adapters and in-flight state during rollout.",
            "owner": "Omar · Senior engineer",
            "state": "planned",
            "alignment": 58,
            "jira": "PAY-250",
            "original": "Existing markets continue working during mixed-version deployment.",
            "current": "Contract fixture ready; migration round-trip work pending.",
            "evidence": "One of two required proof groups complete.",
            "action": "Assign rollback test task before release.",
        },
        {
            "id": "task-contract",
            "parent": "epic-contract",
            "kind": "task",
            "title": "Replay released market contract",
            "summary": "Verify older regional payloads remain accepted.",
            "owner": "Omar · Senior engineer",
            "state": "review",
            "alignment": 76,
            "jira": "PAY-251",
            "original": "Preserve compatibility with existing market adapters.",
            "current": "Fixture replay passes; production consumer inventory needs confirmation.",
            "evidence": "Contract test passes; one human market-ownership question remains.",
            "action": "Confirm all consuming markets with product operations.",
        },
        {
            "id": "epic-drift",
            "parent": "product",
            "kind": "scope branch",
            "title": "Refund eligibility change",
            "summary": "Senior and reviewer agree technically, but work crosses approved product boundary.",
            "owner": "CodeTrust · Routed",
            "state": "needs decision",
            "alignment": 18,
            "jira": "Unlinked",
            "original": "Non-goal: refund authorization policy remains unchanged.",
            "current": "Proposed eligibility window changes from 30 days to 7 days.",
            "evidence": "CT-SCOPE-001 and CT-INTERP-001 cite same product clause and changed line.",
            "action": "Ask product owner: approve new scope, create separate Jira task, or revert change.",
        },
        {
            "id": "commit-drift",
            "parent": "epic-drift",
            "kind": "commit",
            "title": "Tighten refund window",
            "summary": "Correct code and coherent review; wrong product branch until approved.",
            "owner": "Ishan · Senior developer",
            "state": "needs review",
            "alignment": 18,
            "jira": "Missing",
            "commit": "7b91c3a",
            "original": "Refund authorization behavior is explicitly out of scope.",
            "current": "order.age_days <= 30 becomes order.age_days <= 7.",
            "evidence": "Changed refunds/authorization.py:84; reviewer interpretation matches change.",
            "action": "No silent merge. Product decision becomes new branch in intent tree.",
        },
        {
            "id": "decision",
            "parent": "epic-drift",
            "kind": "decision",
            "title": "Product clarification required",
            "summary": "Tree pauses here until business owner accepts or rejects expanded scope.",
            "owner": "Maya · Product",
            "state": "waiting",
            "alignment": 0,
            "jira": "Create on approval",
            "original": "Original product brief remains authoritative revision 3.",
            "current": "Senior interpretation recorded as proposal, not fact.",
            "evidence": "Both interpretations preserved with commit and review provenance.",
            "action": "Decision creates revised product node or closes drift branch.",
        },
        {
            "id": "hackathon-readiness",
            "parent": "product",
            "kind": "assessment",
            "title": "Talent Hack readiness · 69/100",
            "summary": (
                "Competitive enterprise problem and demo story; not win-ready until final "
                "prompt fit and live Jira synchronization are proven."
            ),
            "owner": "CodeTrust · Assessment",
            "state": "needs work",
            "alignment": 69,
            "jira": "July 24–25",
            "original": "Finalists receive a new DTDL problem statement at the build event.",
            "current": (
                "Reusable agent core works; exact challenge alignment and official rubric remain unknown."
            ),
            "evidence": (
                "Problem value 16/20 · differentiation 13/20 · technical execution 15/20 · "
                "integration completeness 11/20 · live demo and clarity 14/20."
            ),
            "action": (
                "Adapt to released prompt. Add live Jira OAuth, one fresh repository run, "
                "measured review-time benefit, and three-minute failure-to-decision demo."
            ),
        },
    ],
}
